name: trial1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  go_router: ^14.3.0
  youtube_player_flutter: ^9.1.1
  flutter_inappwebview: ^6.1.5
  math_expressions: ^2.6.0
  cloud_firestore: ^5.6.1
  firebase_auth: ^5.4.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/logo2.png
    - assets/images/banner.png
    - assets/images/book.jpg
    - assets/.env
fonts:
  - family: Rubik
    fonts:
      - asset: assets/fonts/Rubik-Medium.ttf
      - asset: assets/fonts/Rubik-Bold.ttf
      - asset: assets/fonts/Rubik-ExtraBold.ttf
  - family: Rowdies
    fonts:
      - asset: assets/fonts/Rowdies-bold.ttf