// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByi-t3Vfon9irMgaah-AdD6_dD_jHCOkQ',
    appId: '1:222642084086:web:fa9ace98e1206d5de3f4d7',
    messagingSenderId: '222642084086',
    projectId: 'ppbm-e621',
    authDomain: 'ppbm-e621.firebaseapp.com',
    storageBucket: 'ppbm-e621.firebasestorage.app',
    measurementId: 'G-7LL9HKPCNE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqHvW2q5xXf1HejSofKf50u11CR04eb9Y',
    appId: '1:222642084086:android:5e707cf9b6411ae9e3f4d7',
    messagingSenderId: '222642084086',
    projectId: 'ppbm-e621',
    storageBucket: 'ppbm-e621.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPt6T2x9YkmtrmDWIMNixei3JGBIUhwkg',
    appId: '1:222642084086:ios:2beaaff36389139fe3f4d7',
    messagingSenderId: '222642084086',
    projectId: 'ppbm-e621',
    storageBucket: 'ppbm-e621.firebasestorage.app',
    iosBundleId: 'com.example.trial1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPt6T2x9YkmtrmDWIMNixei3JGBIUhwkg',
    appId: '1:222642084086:ios:2beaaff36389139fe3f4d7',
    messagingSenderId: '222642084086',
    projectId: 'ppbm-e621',
    storageBucket: 'ppbm-e621.firebasestorage.app',
    iosBundleId: 'com.example.trial1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByi-t3Vfon9irMgaah-AdD6_dD_jHCOkQ',
    appId: '1:222642084086:web:873ec9668b1793e6e3f4d7',
    messagingSenderId: '222642084086',
    projectId: 'ppbm-e621',
    authDomain: 'ppbm-e621.firebaseapp.com',
    storageBucket: 'ppbm-e621.firebasestorage.app',
    measurementId: 'G-NVFW33LJTM',
  );
}
